import pyautogui
import time

pyautogui.alert("Para sucesso da execução, não mexa em nada até que o programa termine!")
time.sleep(1)
pyautogui.press('win')
time.sleep(1) 
pyautogui.write("edge")  
time.sleep(1)
pyautogui.click(460,428)   
time.sleep(3) 
pyautogui.press("enter")
time.sleep(3)  
pyautogui.click(359,40)  
pyautogui.write("gmail.com")
time.sleep(1)
pyautogui.press("enter")
time.sleep(7)
pyautogui.write("Email@gmail.com")
time.sleep(3)
pyautogui.press("enter")
time.sleep(7)
pyautogui.write("#SENHAEMAIL")
time.sleep(2)
pyautogui.press("enter")
time.sleep(7)
pyautogui.click(120,150)
time.sleep(5)
pyautogui.write("Emaildestino@gmail.com")
time.sleep(2)
pyautogui.press('enter')
time.sleep(3) 
pyautogui.press('tab')
time.sleep(2)
pyautogui.write("RPA BOM FUTURO")
time.sleep(2)
pyautogui.press('tab')
time.sleep(2)
pyautogui.write("IGNORE ESSE EMAIL É APENAS UM TESTE")
time.sleep(1)
pyautogui.click(849,694)
time.sleep(1) 
pyautogui.click(120,325)